class HasNecrologyPort < ActiveRecord::Migration
  def self.up
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 9;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 16;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 19;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 23;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 24;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 43;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 49;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 52;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 62;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 65;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 71;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 84;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 88;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 94;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 100;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 101;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 103;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 107;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 108;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 111;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 118;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 120;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 128;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 129;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 133;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 134;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 139;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 140;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 144;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 145;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 148;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 152;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 161;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 162;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 166;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 167;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 169;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 180;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 235;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 236;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 238;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 246;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 273;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 280;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 281;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 314;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 315;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 328;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 329;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 337;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 355;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 365;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 401;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 402;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 418;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 468;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 478;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 530;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 535;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 559;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 569;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 600;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 607;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 609;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 614;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 646;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 650;"
    execute "UPDATE books SET has_necrology = TRUE WHERE id = 654;"
  end

  def self.down
  end
end
