UPDATE books SET title = "Aizpute : small town in Latvia ..." WHERE id = 1;
UPDATE books SET title = "Aleksander : `a.y. Lodz' /" WHERE id = 2;
UPDATE books SET title = "Sefer zikaron li-kehilot Vadovitseh\, Andrikhov\, Kalvaryah\," WHERE id = 3;
UPDATE books SET title = "Rahov-Annopol : pirke `edut ve-zikaron /" WHERE id = 4;
UPDATE books SET title = "Antopol : mi-toldoteha shel kehilah ahat be-Polesyah" WHERE id = 5;
UPDATE books SET title = "Jewish people of Arad : life and history /" WHERE id = 6;
UPDATE books SET title = "Atik : a gedenk bukh nakh a Yidisher kehileh in Besarabye /" WHERE id = 7;
UPDATE books SET title = "Sefer yizkor li-kehilat Ogustov veha-sevivah /" WHERE id = 8;
UPDATE books SET title = "Kniga pamiati / Babi Yar book of remembrance" WHERE id = 9;
UPDATE books SET title = "Bobroysk : sefer zikaron li-kehilat Bobroysk u-venoteha" WHERE id = 10;
UPDATE books SET title = "Emlék könyv Nagybánya (Nagysomkút\, Felsöbánya\, Kápolnok Monostor) és környéke zsidóságának tragédiájáról /" WHERE id = 11;
UPDATE books SET title = "Nagybánya és vidéke mártirjainak emlékkönyve /" WHERE id = 12;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 13;
UPDATE books SET title = "Sefer Yizkor : mukdash li-Yehude ha-`ayarot she-nispu ba-sho'ah ba-shanim 1939-44 : Linsk\, Istrik\, Beligrod\, Litovisk veha-sevivah /" WHERE id = 14;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 15;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 16;
UPDATE books SET title = "Baranovits : sefer zikaron /" WHERE id = 17;
UPDATE books SET title = "Baranovitsh in umkum un vidershtand : materyaln un dokumentn\, zikhroyne`s un gvie`s-eyde`sn ... fun hurbm /" WHERE id = 18;
UPDATE books SET title = "Sefer-yizkor Baranov." WHERE id = 19;
UPDATE books SET title = "Be-ovdan moladeti : yad va-shem li-kehilah kedoshah Bardeyov\, Tsekhoslovakyah : mi-yom hivasdah ve-`ad hurbanah." WHERE id = 20;
UPDATE books SET title = "Hayetah `ayarah-- : sefer zikaron li-kehilot Berestets'kah\, Beremelyah veha-sevivah." WHERE id = 21;
UPDATE books SET title = "Volt egyszer egy Dés... Bethlen\, Magyarlápos\, Retteg\," WHERE id = 22;
UPDATE books SET title = "Faces of Zaglembia : 4700 passport photos of Zaglembie Jews\, found in the Jewish Historical Institute in Warsaw and brought to Israel in 1980 by Dr. Arieh Ben-Tov." WHERE id = 23;
UPDATE books SET title = "Pinkas Bendin /" WHERE id = 24;
UPDATE books SET title = "Belkhatov : yizker-bukh : gevidmet dem ondonk fun a farsvundn" WHERE id = 25;
UPDATE books SET title = "Pinkas Belitsah : (Belitse) /" WHERE id = 26;
UPDATE books SET title = "Sefer zikaron li-kedoshe kehilat Bilkeh veha-sevivah." WHERE id = 27;
UPDATE books SET title = "Sefer Baltsi Besarabyah : yad ve-zekher le-Yahadut Baltsi = Bálti Basarabia : a memorial of the Jewish community /" WHERE id = 28;
UPDATE books SET title = "Belz : sefer zikaron /" WHERE id = 29;
UPDATE books SET title = "Kehilat Benderi : sefer zikaron /" WHERE id = 30;
UPDATE books SET title = "Yahadut Berehovo-Beregsas bi-temunot /" WHERE id = 31;
UPDATE books SET title = "Hayetah `ayarah-- : sefer zikaron li-kehilot Berestets'kah\, Beremelyah veha-sevivah." WHERE id = 32;
UPDATE books SET title = "Pinkes fun finf fartilikte kehile`s : Pruzshene\, Bereze\, Maltsh\, Shershev\, Selts : zeyer oyfkum\, geshikhte un umkum /" WHERE id = 33;
UPDATE books SET title = "Bez'ez'ani\, Narayuv veha-sevivah : toldot kehilot she-nehervu /" WHERE id = 34;
UPDATE books SET title = "Mayn shtetele Berezne : zamlung fun zikhroynes fun Berezner landslayt in land un in oysland ... /" WHERE id = 35;
UPDATE books SET title = "Kedoshe sheva kehilot : sefer zikaron lekehilot : Dolha\, Kusnica\, Zadne\, Kerecke\, Bereznik\, Lisicovo\, Sucha-Bronka /" WHERE id = 36;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 37;
UPDATE books SET title = "Bershad : be-tsel `ayarah /" WHERE id = 38;
UPDATE books SET title = "Sefer Bialah-Podlaskah /" WHERE id = 39;
UPDATE books SET title = "Sefer zikaron li-kehilat Byalovz'ig /" WHERE id = 40;
UPDATE books SET title = "Bialistoker yizker bukh / Bialystoker memorial book" WHERE id = 41;
UPDATE books SET title = "Byalistok : bilder album fun a barimter shtot un ire Iden iber der velt : 1200 bilder mit tekst in Idish un in English /" WHERE id = 42;
UPDATE books SET title = "Pinkes Byalistok : grunt-materyaln tsu der geshikhte fun di Yidn in Byalistok biz nokh der ershter velt-milhomeh /" WHERE id = 43;
UPDATE books SET title = "Kartuz-Berezeh : sefer zikaron ve-`edut li-kehilah she-hushmedah\, H.y.d." WHERE id = 44;
UPDATE books SET title = "Sefer-zikaron li-kedoshe 'ayaratenu Baitsh" WHERE id = 45;
UPDATE books SET title = "Bielsk Podlaski : sefer yizkor le-zikhram ha-kadosh shel Yehude Bilsk she-nispu ba-sh'oah ha-na'tsit be-shanim 1939-1944 /" WHERE id = 46;
UPDATE books SET title = "Akerman va-`ayarot ha-mahoz : sefer `edut ve-zikaron /" WHERE id = 47;
UPDATE books SET title = "Bistrits : `ir va-em be-Yi´sra'el : rabaneha u-manhigeha : `avar mefo'ar ve-hoveh `atsuv /" WHERE id = 48;
UPDATE books SET title = "Le-zekher Kehilat Boberka u-venoteha /" WHERE id = 49;
UPDATE books SET title = "Sefer ha-zikaron li-kedoshe Bolihov /" WHERE id = 50;
UPDATE books SET title = "Bonyhád: a destroyed community : the Jews of Bonyhád\, Hungary /" WHERE id = 51;
UPDATE books SET title = "Sefer Borshtshiv = Borszczów /" WHERE id = 52;
UPDATE books SET title = "Brainsk sefer ha-zikaron : a bashraybung fun unzer heym ... /" WHERE id = 53;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 54;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 55;
UPDATE books SET title = "Brisk-d'Lita : oyflag in Yidish." WHERE id = 56;
UPDATE books SET title = "Britshan : Brits'ani ha-Yehudit be-mahatsit ha-me'ah ha-aharonah" WHERE id = 57;
UPDATE books SET title = "Pinkas Britshivah : Britshever pinkas /" WHERE id = 58;
UPDATE books SET title = "Ner tamid\, yizkor li-Brodi : sefer zikaron li-kehilat Brodi u-sevivatah /" WHERE id = 59;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 60;
UPDATE books SET title = "Kedoshe sheva kehilot : sefer zikaron lekehilot : Dolha\, Kusnica\, Zadne\, Kerecke\, Bereznik\, Lisicovo\, Sucha-Bronka /" WHERE id = 61;
UPDATE books SET title = "Bzshezshin yizker-bukh /" WHERE id = 62;
UPDATE books SET title = "Sefer zikaron kehilat Breziv (Bz'ozuv) /" WHERE id = 63;
UPDATE books SET title = "Sefer Butshatsh : matsevet zikaron li-kehilah kedoshah /" WHERE id = 64;
UPDATE books SET title = "Sefer Budzanov /" WHERE id = 65;
UPDATE books SET title = "Ujpesti zsidóság története /" WHERE id = 66;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 67;
UPDATE books SET title = "Sefer Burshtin /" WHERE id = 68;
UPDATE books SET title = "Busk : toldot Yehudeha /" WHERE id = 69;
UPDATE books SET title = "Bihavah : sefer zikaron /" WHERE id = 70;
UPDATE books SET title = "Pinkes Biten : der oyfkum un untergang fun a Yidisher kehile /" WHERE id = 71;
UPDATE books SET title = "Megilat ha-Sho'ah shel kehilat kodesh Tsakovets opcine Cakovec" WHERE id = 72;
UPDATE books SET title = "Sefer Kalarash : le-hantsahat zikhram shel Yehude ha-`ayarah she-nehrevah bi-yeme ha-sho'ah /" WHERE id = 73;
UPDATE books SET title = "Sefer yizkor Maikhov\, Kharshnitsah u-Kshoinz' /" WHERE id = 74;
UPDATE books SET title = "Sefer ha-zikaron li-kehilat Helem : 40 shanah le-hurbanah /" WHERE id = 75;
UPDATE books SET title = "Yizker-bukh Khelm /" WHERE id = 76;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 77;
UPDATE books SET title = "Kishinov ha-Yehudit : `ir va-em be-Shabeshta. `Uvdot ve-ta'arikhim le-divred yameha shel ha-`ir Kishinov be-Beserabyah\, agav bikoret `al ha-sefer" WHERE id = 78;
UPDATE books SET title = "Yehude Kishinov /" WHERE id = 79;
UPDATE books SET title = "Pinkes Khmyelnik : yizker-bukh nokh der horev-gevorener Yidisher kehile /" WHERE id = 80;
UPDATE books SET title = "Sefer zikaron li-kehilat Horzél : Khozshel /" WHERE id = 81;
UPDATE books SET title = "Chrzanów : the life and destruction of a Jewish shtetl /" WHERE id = 82;
UPDATE books SET title = "Tsihanovits\, mehoz Biyalistok : sefer `edut ve-zikaron /" WHERE id = 83;
UPDATE books SET title = "Yizker-bukh fun der Tshekhanover Yidisher kehile = Sefer-yizkor li-kehilat Ts'ehanov /" WHERE id = 84;
UPDATE books SET title = "Sefer zikaron di-kehilah kedoshah Tsyeshinov /" WHERE id = 85;
UPDATE books SET title = "Kolozsvári zsidóság emlékkönyve /" WHERE id = 86;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 87;
UPDATE books SET title = "Churban Czenstochow = the destruction of Czenstokov /" WHERE id = 88;
UPDATE books SET title = "Czenstochov\, our legacy /" WHERE id = 89;
UPDATE books SET title = "Sefer Tshenstohov.[Sifre zikaron li-kehilot ha-golah]" WHERE id = 90;
UPDATE books SET title = "Tshenstokhov : nayer tsugab-material tsum bukh Tshenstokhover Yidn /" WHERE id = 91;
UPDATE books SET title = "Tshenstokhover Yidn." WHERE id = 92;
UPDATE books SET title = "Yizker-bukh : nokh der horev-gevorener Yidisher kehile Tshizsheve /" WHERE id = 93;
UPDATE books SET title = "Dubrowa : (Dabrowa Bialostocka) : memorial to a shtetl /" WHERE id = 94;
UPDATE books SET title = "Sefer kehilat Yehude Dombrovah Gurnitsheh ve-hurbanah /" WHERE id = 95;
UPDATE books SET title = "Dorot shel Yahadut ve-Tsiyonut Dorohoi : Saven\, Mikha'ilen\, Daraban\, Hertsah\, Rada'uts-Prut /" WHERE id = 96;
UPDATE books SET title = "Esh tamid--yizkor le-Dolhinov : sefer zikaron li-kehilat Dolhinov veha-sevivah /" WHERE id = 97;
UPDATE books SET title = "Memorial book of David-Horodok /" WHERE id = 98;
UPDATE books SET title = "Sefer zikaron David-Horodok /" WHERE id = 99;
UPDATE books SET title = "Sefer Dembits /" WHERE id = 100;
UPDATE books SET title = "Demblin-Modzjitz book /" WHERE id = 101;
UPDATE books SET title = "Sefer Demblin-Modzhits /" WHERE id = 102;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 103;
UPDATE books SET title = "Volt egyszer egy Dés... Bethlen\, Magyarlápos\, Retteg\, Nagyilonda és környéke." WHERE id = 104;
UPDATE books SET title = "Lubts' ve-Delatits' : sefer zikaron /" WHERE id = 105;
UPDATE books SET title = "Sefer Derets'in = The Dereczin memorial book : a book of remembrance honoring the communities of Dereczin\, Halinka\, Kolonia-Sinaiska /" WHERE id = 106;
UPDATE books SET title = "Sefer zikaron li-Yehude Derets'keh u-geliloteha /" WHERE id = 107;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 108;
UPDATE books SET title = "Sefer Rubiz'evits'\, Derevnah veha-sevivah /" WHERE id = 109;
UPDATE books SET title = "Sefer zikhron Stoyebts-Sverz'no veha-`ayarot ha-semukhot Rubezevits\, Derevno\, Nalibok /" WHERE id = 110;
UPDATE books SET title = "Sefer Divenishak : yad va-shem le-`ayarah Yehudit = Devenishki book : memorial book = Sefer Divenishok : geshikhte fun a shtetl /" WHERE id = 111;
UPDATE books SET title = "Disnah : sefer zikaron li-kehilah /" WHERE id = 112;
UPDATE books SET title = "Sefer Yekaterinoslav-Dnepropetrovsk : ha-kehilah ha-Yehudit me-hivasdah ve-`ad ha-yom /" WHERE id = 113;
UPDATE books SET title = "Sefer zikaron le-zekher Kehilat Dobromil ve-Nayshtut /" WHERE id = 114;
UPDATE books SET title = "`Ayarati : sefer zikaron la-`ayarot Dobzhyn-Golov /" WHERE id = 115;
UPDATE books SET title = "Dorot shel Yahadut ve-Tsiyonut Dorohoi : Saven\, Mikha'ilen\, Daraban\, Hertsah\, Rada'uts-Prut /" WHERE id = 116;
UPDATE books SET title = "Kedoshe sheva kehilot : sefer zikaron lekehilot : Dolha\, Kusnica\, Zadne\, Kerecke\, Bereznik\, Lisicovo\, Sucha-Bronka /" WHERE id = 117;
UPDATE books SET title = "Dubosari : sefer zikaron /" WHERE id = 118;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 119;
UPDATE books SET title = "Dubno : sefer zikaron." WHERE id = 120;
UPDATE books SET title = "Sefer Dombroven : Ner-zikaron lamoshava ha-hakla'it ha-Yehudit hari'shona be-Besaravya /" WHERE id = 121;
UPDATE books SET title = "Sefer ha-zikaron li-kehilat Dunaserdaheli /" WHERE id = 122;
UPDATE books SET title = "Hurbn Glubok\, Sharkoystsene\, Dunilovitsh\, Postav\, Droye\, Kazan : dos lebn un umkum fun yidishn shtetlekh in Vaysrusland-Lite (Vilne gegent) /" WHERE id = 123;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 124;
UPDATE books SET title = "`Ayarah hayetah be-Lita : Dusyat bi-re'i ha-zikhronot /" WHERE id = 125;
UPDATE books SET title = "Pinkes Zshetl : tsum 15-ten yortag noch dem groyzamen hurbm fun unzer gevezener haym /" WHERE id = 126;
UPDATE books SET title = "Koydenov : zamlbukh tsum ondenk fun di Koydenover kedoyshim ... /" WHERE id = 127;
UPDATE books SET title = "Sefer yizkor shel kehilat Dzialoshits veha-sevivah." WHERE id = 128;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 129;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 130;
UPDATE books SET title = "Aisheshuk : koroteha ve-hurbanah : pirke zikhronot ve-eduyot" WHERE id = 131;
UPDATE books SET title = "Kehilot Turets ve-Yeremits : sefer zikaron /" WHERE id = 132;
UPDATE books SET title = "Sefer zikaron li-Yehude Derets'keh u-geliloteha /" WHERE id = 133;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 134;
UPDATE books SET title = "Sefer Falenits /" WHERE id = 135;
UPDATE books SET title = "Hurban Otvotsk\, Falenits\, Kartshev /" WHERE id = 136;
UPDATE books SET title = "`Ayaratenu leshe-`avar Feherdarmat /" WHERE id = 137;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 138;
UPDATE books SET title = "Sefer Frampol /" WHERE id = 139;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of" WHERE id = 140;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 141;
UPDATE books SET title = "Gombin : the life and destruction of a Jewish town in Poland /" WHERE id = 142;
UPDATE books SET title = "Sefer Gorzd\, Lita : `ayarah be-hayeha uve-khilyonah = Gargzdai /" WHERE id = 143;
UPDATE books SET title = "Garvolin yisker bukh = Garvolin\, sefer zikaron /" WHERE id = 144;
UPDATE books SET title = "Sefer zikaron shel kedoshe `ayarotenu Samoshuivar-Iklod veha-sevivah /" WHERE id = 145;
UPDATE books SET title = "Memorial book of Glebokie : a translation into English of Khurbn Glubok [sic] by M. & Z. Rajak which was originally published in 1956 in Yiddish in B" WHERE id = 146;
UPDATE books SET title = "Hurbn Glubok\, Sharkoystsene\, Dunilovitsh\, Postav\, Droye\, Kazan : dos lebn un umkum fun yidishn shtetlekh in Vaysrusland-Lite (Vilne gegent) /" WHERE id = 147;
UPDATE books SET title = "Sefer Gnivoshov /" WHERE id = 148;
UPDATE books SET title = "Lebn un umkum fun Olshan /" WHERE id = 149;
UPDATE books SET title = "`Ayarati : sefer zikaron la-`ayarot Dobzhyn-Golov /" WHERE id = 150;
UPDATE books SET title = "Sefer Derets'in = The Dereczin memorial book : a book of remembrance honoring the communities of Dereczin\, Halinka\, Kolonia-Sinaiska /" WHERE id = 151;
UPDATE books SET title = "Sefer yizkor Gonyondz = Yizker bukh Gonyondz." WHERE id = 152;
UPDATE books SET title = "Megile´s Ger : geheilikt dem ondenk fun di kedoyshim u-tehoyrim fun undzer haruv gevorener geboyrn-shtot Ger - Gura-Kalvarya in Poyln : ma" WHERE id = 153;
UPDATE books SET title = "Sefer Gorlitsah : ha-kehilah be-vinyanah uve-hurbanah." WHERE id = 154;
UPDATE books SET title = "Pinkes Gostynin : yizkor bukh /" WHERE id = 155;
UPDATE books SET title = "Govorovah : sefer-zikaron /" WHERE id = 156;
UPDATE books SET title = "Sefer ha-zikaron li-kehilat Grabovits." WHERE id = 157;
UPDATE books SET title = "Grayeve yisker-bukh /" WHERE id = 158;
UPDATE books SET title = "Megile`s Gritse /" WHERE id = 159;
UPDATE books SET title = "Felshtin : zamlbukh tsum ondenk fun di Felshtiner kedoyshim /" WHERE id = 160;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 161;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 162;
UPDATE books SET title = "Zikhron netsah la-kehilot ha-kedoshot Halmin-Turts veha-sevivah asher nehrevu ba-sho'ah : hantsahat kehilot ha-kodesh Halmin-Turts veha-se" WHERE id = 163;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 164;
UPDATE books SET title = "Dorot shel Yahadut ve-Tsiyonut Dorohoi : Saven\, Mikha'ilen\, Daraban\, Hertsah\, Rada'uts-Prut /" WHERE id = 165;
UPDATE books SET title = "Hurbm Glinyane (Gline) : lezikoren unzere kdoyshim." WHERE id = 166;
UPDATE books SET title = "Megile`s Gline (Glinyane) : zikhroyne`s un iberlebungen fun a horev gevorener kehile." WHERE id = 167;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 168;
UPDATE books SET title = "Sefer Horodenka /" WHERE id = 169;
UPDATE books SET title = "Kehilat Horodlah : sefer zikaron li-kedoshe Horodlah\, Polin\, veli-kedoshe ha-kefarim ha-semukhim /" WHERE id = 170;
UPDATE books SET title = "Sefer zikaron li-kehilat Horodok (`a. y. Byalistok) /" WHERE id = 171;
UPDATE books SET title = "Sefer Horokhov /" WHERE id = 172;
UPDATE books SET title = "Seyfer Hosht : yizker-bukh /" WHERE id = 173;
UPDATE books SET title = "Grodnah-Grodne /" WHERE id = 174;
UPDATE books SET title = "Pinkas Hrubishov : li-melot `e´srim shanah le-hurban `ir huladetenu /" WHERE id = 175;
UPDATE books SET title = "Husyatin\, Podolyer gubernye : Idisher yishev\, gegrindet in 16-tn yorhundert\, umgebrakht in 1942 : le-zikhron netsah /" WHERE id = 176;
UPDATE books SET title = "City in flames : memorial book of Yampol (District of Volhyn) /" WHERE id = 177;
UPDATE books SET title = "Matsevet zikaron li-kehilat Yavorov veha-sevivah" WHERE id = 178;
UPDATE books SET title = "Ilan ve-shorashav : sefer korot Tal : Zofyovkah--Ignatovkah /" WHERE id = 179;
UPDATE books SET title = "Sefer zikaron shel kedoshe `ayarotenu Samoshuivar-Iklod veha-sevivah /" WHERE id = 180;
UPDATE books SET title = "Volt egyszer egy Dés... Bethlen\, Magyarlápos\, Retteg\, Nagyilonda és környéke." WHERE id = 181;
UPDATE books SET title = "Örökmeécses : Sahy-Ipoolyság és környéke /" WHERE id = 182;
UPDATE books SET title = "Sefer zikaron li-kehilat Ivyeh /" WHERE id = 183;
UPDATE books SET title = "Sokolievka/Justingrad : a century of struggle and suffering in a Ukrainian shtetl\, as recounted by survivors to its scattered descendants /" WHERE id = 184;
UPDATE books SET title = "Sefer yizkor li-kehilat Trembovlah Strusov ve-Yanov veha-sevivah." WHERE id = 185;
UPDATE books SET title = "Sefer Ivenits\, Kamen\, veha-sevivah." WHERE id = 186;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 187;
UPDATE books SET title = "Sefer Yadov = Yadov-bukh /" WHERE id = 188;
UPDATE books SET title = "Sefer Yaroslav : gal-`ed li-zekher `irenu = Jaroslaw /" WHERE id = 189;
UPDATE books SET title = "Sefer ha-zikaron li-Yehude Yendjyov... /" WHERE id = 190;
UPDATE books SET title = "Le-zikhram shel kedoshe kehilat Yeznah she-nispu bi-shenat 701 /" WHERE id = 191;
UPDATE books SET title = "Sefer Yanovah : le-hantsahat zikhram shel Yehude ha-`ayarah she-neherevah ba-Sho'ah /" WHERE id = 192;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 193;
UPDATE books SET title = "Sefer ha-zikaron li-kehilat Yurburg-Lita /" WHERE id = 194;
UPDATE books SET title = "Kalish book /" WHERE id = 195;
UPDATE books SET title = "Sefer Kalish." WHERE id = 196;
UPDATE books SET title = "Toldot Yehude Kalish." WHERE id = 197;
UPDATE books SET title = "Kalush : hayeha ve-hurbanah shel ha-kehilah /" WHERE id = 198;
UPDATE books SET title = "Kehilat Kalushin /" WHERE id = 199;
UPDATE books SET title = "Sefer Kalushin : gehaylikt der horev gevorener kehile /" WHERE id = 200;
UPDATE books SET title = "Sefer zikaron li-kehilot Vadovitseh\, Andrikhov\, Kalvaryah\, Mishlenits\, Suka /" WHERE id = 201;
UPDATE books SET title = "Sefer yizkor li-kehilot Kamenits de-Lita\, Zastavyah veha-kolonyot /" WHERE id = 202;
UPDATE books SET title = "Kamenets-Podolsk u-sevivatah : sefer zikaron li-kehilot Yi´sra'el..." WHERE id = 203;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 204;
UPDATE books SET title = "Kaminits-Podolsk : excerpts from Kaminits-Podolsk u-sevivatah : a memorial book /" WHERE id = 205;
UPDATE books SET title = "Sefer ha-zikaron li-Kehilat Kamin-Koshirski veha-sevivah /" WHERE id = 206;
UPDATE books SET title = "Kapresht\, `ayaratenu : sefer zikaron le-kehilah yehudit be-Besarabyah = Undzer shtetele Kapresht : a gedank-bukh nakh a Yidisher kehilah in" WHERE id = 207;
UPDATE books SET title = "Karcagi zsidók története /" WHERE id = 208;
UPDATE books SET title = "Yizkor-bukh tsu fareyvikn dem andenk fun di horev-gevorene Yidishe kehiles Otvotsk\, Kartshev /" WHERE id = 209;
UPDATE books SET title = "Hurban Otvotsk\, Falenits\, Kartshev /" WHERE id = 210;
UPDATE books SET title = "Toldot Yehudi Kastoriyah" WHERE id = 211;
UPDATE books SET title = "Katovits : perihatah u-sheki`atah shel ha-kehilah ha-Yehudit : sefer zikaron /" WHERE id = 212;
UPDATE books SET title = "Ven di Vaysl hot geredt Yidish" WHERE id = 213;
UPDATE books SET title = "Kedoshe sheva kehilot : sefer zikaron lekehilot : Dolha\, Kusnica\, Zadne\, Kerecke\, Bereznik\, Lisicovo\, Sucha-Bronka /" WHERE id = 214;
UPDATE books SET title = "Rákospalotai Zsidó Hitközség története /" WHERE id = 215;
UPDATE books SET title = "Yehude Kaz'marok veha-sevivah bi-tekufat ha-Sho'ah /" WHERE id = 216;
UPDATE books SET title = "Sefer Horostkov = Chorostkow book /" WHERE id = 217;
UPDATE books SET title = "Sefer Kehilat Hotin (Besarabyah) /" WHERE id = 218;
UPDATE books SET title = "Sefer Kelts." WHERE id = 219;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 220;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 221;
UPDATE books SET title = "Pinkas Kletsk /" WHERE id = 222;
UPDATE books SET title = "Book of Kobrin : the scroll of life and destruction /" WHERE id = 223;
UPDATE books SET title = "Sefer Kobrin : megilat hayyim ve-hurban /" WHERE id = 224;
UPDATE books SET title = "Sefer Kotsk /" WHERE id = 225;
UPDATE books SET title = "Pinkes Kolbushov : Kolbsov /" WHERE id = 226;
UPDATE books SET title = "Kolno memorial book /" WHERE id = 227;
UPDATE books SET title = "Sefer Kolo : finfhundert yor Yidish Kolo /" WHERE id = 228;
UPDATE books SET title = "Pinkes Kolomey : geshikhte\, zikhroyne´s\, geshtaltn\, hurbn /" WHERE id = 229;
UPDATE books SET title = "Sefer zikaron li-kehilat Kolomeyah veha-sevivah /" WHERE id = 230;
UPDATE books SET title = "Sefer Derets'in = The Dereczin memorial book : a book of remembrance honoring the communities of Dereczin\, Halinka\, Kolonia-Sinaiska /" WHERE id = 231;
UPDATE books SET title = "Bet Komarna : korot ha-`ir ve-toldoteha\, me-hivasdah ve-`ad hurbanah\, rabaneha\, gedoleha\, va-`admoreha\, isheha\, hayehem\, ve-khilyonam /" WHERE id = 232;
UPDATE books SET title = "`Edut me'uheret /" WHERE id = 233;
UPDATE books SET title = "Kehilat Konin bi-ferihatah uve-hurbanah /" WHERE id = 234;
UPDATE books SET title = "Sefer zikaron li-Yehude Derets'keh u-geliloteha /" WHERE id = 235;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 236;
UPDATE books SET title = "Sefer Pokshivnitsah /" WHERE id = 237;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 238;
UPDATE books SET title = "Kortshin (Kortshina) Sefer zikaron\, Gedenk-bukh ... /" WHERE id = 239;
UPDATE books SET title = "Korelits-Korelitsh : hayeha ve-hurbanah shel kehilah Yehudit = kiyum un hurben fun a Yidisher kehileh /" WHERE id = 240;
UPDATE books SET title = "Korits (Vohlin) : sefer zikaron li-kehilatenu she-`alah `aleha ha-koret /" WHERE id = 241;
UPDATE books SET title = "Kassai zsidóság története és gallériája /" WHERE id = 242;
UPDATE books SET title = "Sefer Kosov (Galitsyah ha-mizrahit) /" WHERE id = 243;
UPDATE books SET title = "Kosow Lacki." WHERE id = 244;
UPDATE books SET title = "Jews of Kaszony\, Subcarpathia /" WHERE id = 245;
UPDATE books SET title = "Pinkes Kovel /" WHERE id = 246;
UPDATE books SET title = "Yizkor Kehilot Luninets - Ko´zanhorodok /" WHERE id = 247;
UPDATE books SET title = "Book of Kozienice : on the 27th anniversary of the savage destruction of our former home /" WHERE id = 248;
UPDATE books SET title = "Sefer Kozshenits : tsum 27tn yortog nokh dem groyzamen hurbm fun undzer gevezener heym /" WHERE id = 249;
UPDATE books SET title = "Sefer Krako : `ir ve-em be-Yi´sra'el /" WHERE id = 250;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 251;
UPDATE books SET title = "Sefer Krashnik /" WHERE id = 252;
UPDATE books SET title = "Krasnobrod : sefer zikaron /" WHERE id = 253;
UPDATE books SET title = "Yizker tsum ondenk fun di kedoyshey Krasnistov /" WHERE id = 254;
UPDATE books SET title = "Pinkas Kremenits : sefer zikaron /" WHERE id = 255;
UPDATE books SET title = "Ner tamid : yizkor le-Krivits'\, li-kehilah she-nikhretah" WHERE id = 256;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 257;
UPDATE books SET title = "Sefer yizkor Maikhov\, Kharshnitsah u-Kshoinz' /" WHERE id = 258;
UPDATE books SET title = "Vlotslavek veha-sevivah : sefer zikaron /" WHERE id = 259;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 260;
UPDATE books SET title = "Yizker-bukh Koriv = Sefer yizkor : matsevet zikaron le-`ayaratenu Koriv = Izkor book : in memoriam of our home-town Kurów /" WHERE id = 261;
UPDATE books SET title = "Kedoshe sheva kehilot : sefer zikaron lekehilot : Dolha\, Kusnica\, Zadne\, Kerecke\, Bereznik\, Lisicovo\, Sucha-Bronka /" WHERE id = 262;
UPDATE books SET title = "Sefer Kutnah veha-sevivah /" WHERE id = 263;
UPDATE books SET title = "Kitov `iri : bene Kuti mesaprim et sipur ha-`ir /" WHERE id = 264;
UPDATE books SET title = "Rishonim la-mered : Lahva /" WHERE id = 265;
UPDATE books SET title = "Lantsut : hayeha ve-hurbanah shel kehilah Yehudit /" WHERE id = 266;
UPDATE books SET title = "Albom zahavzikronot mi-yaldutenu arba`ah dorot shel kehilat" WHERE id = 267;
UPDATE books SET title = "Sefer Lintshits /" WHERE id = 268;
UPDATE books SET title = "Kehilat Lenin : Sefer Zikaron." WHERE id = 269;
UPDATE books SET title = "Sefer Yizkor : mukdash li-Yehude ha-`ayarot she-nispu ba-sho'ah ba-shanim 1939-44 : Linsk\, Istrik\, Beligrod\, Litovisk veha-sevivah /" WHERE id = 270;
UPDATE books SET title = "Tragedy of the Letichev Ghetto /" WHERE id = 271;
UPDATE books SET title = "Sefer Lida /" WHERE id = 272;
UPDATE books SET title = "Jews in Liepaja\, Latvia\, 1941-45 : a memorial book /" WHERE id = 273;
UPDATE books SET title = "Kehilat Lipkani : sefer zikaron." WHERE id = 274;
UPDATE books SET title = "Lipkan fun amol /" WHERE id = 275;
UPDATE books SET title = "Kedoshe sheva kehilot : sefer zikaron lekehilot : Dolha\, Kusnica\, Zadne\, Kerecke\, Bereznik\, Lisicovo\, Sucha-Bronka /" WHERE id = 276;
UPDATE books SET title = "Luboml : the memorial book of a vanished shtetl /" WHERE id = 277;
UPDATE books SET title = "Sefer yizkor li-kehilat Luboml /" WHERE id = 278;
UPDATE books SET title = "Geshikhte fun yidn in Lodzsh in di yorn fun der deytsher yidn-oysratung /" WHERE id = 279;
UPDATE books SET title = "Lodz - names : list of the ghetto inhabitants 1940-1944" WHERE id = 280;
UPDATE books SET title = "Lodz names : list of the ghetto inhabitants 1940-1944 published by Yad Vashem and the Organization of Former Residents of Lodz in Israel." WHERE id = 281;
UPDATE books SET title = "Lodzsh shel mayle : dos Yidishe gaystike un derhoybene Lodzsh : 100 yor Yidishe un Hebreishe literatur un kultur in Lodzsh..." WHERE id = 282;
UPDATE books SET title = "Lodzsher yizker-bukh." WHERE id = 283;
UPDATE books SET title = "Sefer Yizkor li-kehilat Lokats' (Polin) = Gedenk bukh far di shtetl Lokatsh /" WHERE id = 284;
UPDATE books SET title = "Lomzshe : ir oyfkum un untergang /" WHERE id = 285;
UPDATE books SET title = "Sefer zikaron li-kehilat Lomzah /" WHERE id = 286;
UPDATE books SET title = "Loshits : le-zeykher an umgebrakhter kehile" WHERE id = 287;
UPDATE books SET title = "Hurben Levertov : a matseyve Levertov un Levertover kdoyshim /" WHERE id = 288;
UPDATE books SET title = "Bukh fun Lublin : zikhroynes\, gvies-eydes un materialn iber lebn\, kamf un martirertum fun lubliner yidishn yishev." WHERE id = 289;
UPDATE books SET title = "Lublin /" WHERE id = 290;
UPDATE books SET title = "Seyfer Lukov : geheylikt der horev gevorener kehile /" WHERE id = 291;
UPDATE books SET title = "Yizkor Kehilot Luninets - Ko´zanhorodok /" WHERE id = 292;
UPDATE books SET title = "Sefer Yizkor : mukdash li-Yehude ha-`ayarot she-nispu ba-sho'ah ba-shanim 1939-44 : Linsk\, Istrik\, Beligrod\, Litovisk veha-sevivah /" WHERE id = 293;
UPDATE books SET title = "Sefer Lutsk." WHERE id = 294;
UPDATE books SET title = "Lvov." WHERE id = 295;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 296;
UPDATE books SET title = "Lubts' ve-Delatits' : sefer zikaron /" WHERE id = 297;
UPDATE books SET title = "Kehilah ha-Yehudit shel Mád\, Hungaryah /" WHERE id = 298;
UPDATE books SET title = "Sefer zikaron li-kehilat Makov-Mazovitsk /" WHERE id = 299;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 300;
UPDATE books SET title = "Pinkes fun finf fartilikte kehile`s : Pruzshene\, Bereze\, Maltsh\, Shershev\, Selts : zeyer oyfkum\, geshikhte un umkum /" WHERE id = 301;
UPDATE books SET title = "Sefer Marmarosh : me'ah ve-shishim kehilot kedoshot be-yishuvan uve-hurbanan /" WHERE id = 302;
UPDATE books SET title = "Sefer Zikhron kedoshim li-Yehude Karpatoros-Maramuresh : le-hantsahat zekher ha-kehilot ha-kedoshot ... /" WHERE id = 303;
UPDATE books SET title = "Markuleshti : yad le-moshavah yehudit be-Besarabyah /" WHERE id = 304;
UPDATE books SET title = "Melnitsah : pelekh Vohlin\, Ukra'inah : sefer hantsahah\, `edut ve-zikaron li-kehilat Melnitsah /" WHERE id = 305;
UPDATE books SET title = "Horodets : a geshikhte fun a shtetl (1142-1942) /" WHERE id = 306;
UPDATE books SET title = "Meziritsh gadol be-vinyana uve-hurbana : 'Irgun `ole Meziritsh be-Yi´sra'el\, Taf Shin Tet Vav." WHERE id = 307;
UPDATE books SET title = "Sefer Mikhalovtsah veha-sevivah /" WHERE id = 308;
UPDATE books SET title = "Sefer yizkor Maikhov\, Kharshnitsah u-Kshoinz' /" WHERE id = 309;
UPDATE books SET title = "Mezritsh : zamlbukh in heylikn ondenk fun di umgekumene Yidn" WHERE id = 310;
UPDATE books SET title = "Sefer Mezritsh : le-zeker kedoshe `irenu ha-yud-daled.." WHERE id = 311;
UPDATE books SET title = "Remembering Mielec : the destruction of the Jewish community /" WHERE id = 312;
UPDATE books SET title = "Dorot shel Yahadut ve-Tsiyonut Dorohoi : Saven\, Mikha'ilen\, Daraban\, Hertsah\, Rada'uts-Prut /" WHERE id = 313;
UPDATE books SET title = "Sefer zikaron li-Yehude Derets'keh u-geliloteha /" WHERE id = 314;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 315;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 316;
UPDATE books SET title = "Sefer zikaron li-kehilot Rembertov\, Okunyev\, Milosnah /" WHERE id = 317;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 318;
UPDATE books SET title = "Albom Minsk : mivhar tatslumim /" WHERE id = 319;
UPDATE books SET title = "Minsk `ir va-'em : korot\, ma`a´sim\, ishim\, havi /" WHERE id = 320;
UPDATE books SET title = "Sefer Minsk-Mazovitsk : yizker-bukh nokh der horev-gevorener kehile Minsk-Mazovietsk /" WHERE id = 321;
UPDATE books SET title = "Sefer Mir /" WHERE id = 322;
UPDATE books SET title = "Miskolc és környéke màrtírkönyve : a szent gyülekezetek Hidasnémetitöl\, Mezökövesdig és Ózdtól Szerencsig /" WHERE id = 323;
UPDATE books SET title = "Mizoch : sefer zikaron." WHERE id = 324;
UPDATE books SET title = "Mlavah ha-Yehudit : koroteha\, hitpathutah\, kilyonah = Di Yidishe Mlave : geshikhte\, oyfshtayg\, umkum = Jewish Mlawa : its history\, development\," WHERE id = 325;
UPDATE books SET title = "Pinkes Mlave /" WHERE id = 326;
UPDATE books SET title = "Sefer Mlinov-Muravits /" WHERE id = 327;
UPDATE books SET title = "Sefer zikaron li-Yehude Derets'keh u-geliloteha /" WHERE id = 328;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 329;
UPDATE books SET title = "Pyesk u-Most : sefer yizkor." WHERE id = 330;
UPDATE books SET title = "Sefer-zikaron li-kehilat Meytshet /" WHERE id = 331;
UPDATE books SET title = "Pinkes Zshirardov\, Amshinov un Viskit : Yizker-bukh" WHERE id = 332;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 333;
UPDATE books SET title = "Sefer Mlinov-Muravits /" WHERE id = 334;
UPDATE books SET title = "Sefer zikaron li-kehilot Vadovitseh\, Andrikhov\, Kalvaryah\, Mishlenits\, Suka /" WHERE id = 335;
UPDATE books SET title = "Nadvurnah : sefer `edut ve-zikaron /" WHERE id = 336;
UPDATE books SET title = "A kállói cádik; a nagykállói zsidóság története\," WHERE id = 337;
UPDATE books SET title = "Karcagi zsidók története /" WHERE id = 338;
UPDATE books SET title = "`Ayaratenu Nalibok : hayeha ve-hurbanah." WHERE id = 339;
UPDATE books SET title = "Sefer zikhron Stoyebts-Sverz'no veha-`ayarot ha-semukhot Rubezevits\, Derevno\, Nalibok /" WHERE id = 340;
UPDATE books SET title = "Sefer Kobilnik /" WHERE id = 341;
UPDATE books SET title = "Pinkas Navaredok /" WHERE id = 342;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 343;
UPDATE books SET title = "Sefer Nisviz' /" WHERE id = 344;
UPDATE books SET title = "Die Verfolgung der Norhhauser Juden 1933 bis 1945" WHERE id = 345;
UPDATE books SET title = "Zvhil (Novogradvolinsk) /" WHERE id = 346;
UPDATE books SET title = "Novoselitsah /" WHERE id = 347;
UPDATE books SET title = "Zikhron Novoselitasah (Beserabyah) : goralot ba-Shoah /" WHERE id = 348;
UPDATE books SET title = "Vlastivedný sborník okresu Nový Jicín." WHERE id = 349;
UPDATE books SET title = "Hurbn Yaritshov bay Lemberg : a kurtse beshraybung funem Tsveyten velt-krieg un fun dem leben un hurbn fun a Idish shtetil in Poylen\, mit" WHERE id = 350;
UPDATE books SET title = "Sefer-zikaron li-kehilot Shts'uts'in\, Vasilishki\, Ostrin\, Novidbor\, Roz'anke /" WHERE id = 351;
UPDATE books SET title = "Pinkas Novi-Devor /" WHERE id = 352;
UPDATE books SET title = "Seyfer Sants /" WHERE id = 353;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 354;
UPDATE books SET title = "Gedenkbuch für die Nürnberger Opfer der Schoa /" WHERE id = 355;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 356;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 357;
UPDATE books SET title = "Sefer zikaron li-kehilot Rembertov\, Okunyev\, Milosnah /" WHERE id = 358;
UPDATE books SET title = "Olkush = (Elkish) : sefer zikaron li-kehilah she-hukhadah ba-Sho'ah /" WHERE id = 359;
UPDATE books SET title = "Pinkas ha-kehilah Olika : sefer yizkor /" WHERE id = 360;
UPDATE books SET title = "Apt : (Opatov); sefer zikaron le-`ir ve-em be-Yi´sra'el asher hayetah ve-enenah `od. Yizker-bukh tsum ondenk fun undzer …." WHERE id = 361;
UPDATE books SET title = "Reshimat Yehude `ir ha-mahoz Optov meha-shanim 1940-41 = The list of the Jewish people of the district city of Opatow in the years 1940-1941 /" WHERE id = 362;
UPDATE books SET title = "Sefer Opots'nah : yad va-shem la-kehilah she-harvah /" WHERE id = 363;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 364;
UPDATE books SET title = "Sefer zikaron le-Yahadut Grosvardain-Orade'aeh-Nag'varad veha-sevivah\, mi-shenat yesudah ve-`ad hurbanah." WHERE id = 365;
UPDATE books SET title = "Tegnap városa : a nagyváradi zsidóság emlékkönyve /" WHERE id = 366;
UPDATE books SET title = "Székelyudvarkhely megye zsidóságának szenvedése a Nácizmus alatt /" WHERE id = 367;
UPDATE books SET title = "Orheyov be-vinyanah uve-hurbanah /" WHERE id = 368;
UPDATE books SET title = "Sefer Z'eludok ve-Orlovah : gal`ed le-zikaron /" WHERE id = 369;
UPDATE books SET title = "Sefer zikaron li-kehilat Oshminah /" WHERE id = 370;
UPDATE books SET title = "Sefer-zikaron li-kehilot Shts'uts'in\, Vasilishki\, Ostrin\, Novidbor\, Roz'anke /" WHERE id = 371;
UPDATE books SET title = "Pinkas Ostra'ah : sefer zikaron li-kehilat Ostra'ah /" WHERE id = 372;
UPDATE books SET title = "Sefer Ostra'ah : (Vohlin) : matsevet zikaron li-kehilah kedoshah = Ostrog book /" WHERE id = 373;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 374;
UPDATE books SET title = "Sefer kehilat Ostrolenkah = Bukh fun Ostrolenker kehilah /" WHERE id = 375;
UPDATE books SET title = "Ostrov Mazovyetsk /" WHERE id = 376;
UPDATE books SET title = "Sefer-ha-zikaron li-kehilat Ostrov-Mazovyetsk /" WHERE id = 377;
UPDATE books SET title = "Ostrovtse." WHERE id = 378;
UPDATE books SET title = "Sefer Ostrovtseh : le-zikaron ule-`edut /" WHERE id = 379;
UPDATE books SET title = "Yizkor-bukh tsu fareyvikn dem andenk fun di horev-gevorene Yidishe kehiles Otvotsk\, Kartshev /" WHERE id = 380;
UPDATE books SET title = "Hurban Otvotsk\, Falenits\, Kartshev /" WHERE id = 381;
UPDATE books SET title = "Sefer Ozyeran veha-sevivah." WHERE id = 382;
UPDATE books SET title = "Ozarkov /" WHERE id = 383;
UPDATE books SET title = "Sefer Pabyanits : yizker-bukh fun der farpaynikter kehileh /" WHERE id = 384;
UPDATE books SET title = "Pápai zsidóság emlékkönyve : a mártirhalált halt pápai és környékbeli zsidók emlékére /" WHERE id = 385;
UPDATE books SET title = "Pyesk u-Most : sefer yizkor." WHERE id = 386;
UPDATE books SET title = "Sefer Podhaytsah /" WHERE id = 387;
UPDATE books SET title = "Sefer Podvolots'iskah veha-sevivah /" WHERE id = 388;
UPDATE books SET title = "Pinsk lo tishakhah" WHERE id = 389;
UPDATE books SET title = "Pinsk : sefer `edut ve-zikaron li-kehilat Pinsk-Karlin /" WHERE id = 390;
UPDATE books SET title = "Toyznt yor Pinsk : geshikhte fun der shtot\, der Yidisher yishuv\, institutsies... /" WHERE id = 391;
UPDATE books SET title = "Piotrkov Tribunalski veha-sevivah : sefer zikaron ... /" WHERE id = 392;
UPDATE books SET title = "Tale of one city : Piotrków Trybunalski /" WHERE id = 393;
UPDATE books SET title = "Plotsk : bletlekh geshikhte fun Idishn lebn in der alter heym /" WHERE id = 394;
UPDATE books SET title = "Plotsk : toldot kehilah `atikat-yamin be-Polin /" WHERE id = 395;
UPDATE books SET title = "We remember Jewish Plock! /" WHERE id = 396;
UPDATE books SET title = "Yidn in Plotsk /" WHERE id = 397;
UPDATE books SET title = "Sefer Plonsk veha-sevivah : Neishtat ve-Sokhotsin : yad ve-zekher li-kehilot she-nehrevu /" WHERE id = 398;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 399;
UPDATE books SET title = "Pitshayever yizker bukh /" WHERE id = 400;
UPDATE books SET title = "Sefer zikaron li-Yehude Derets'keh u-geliloteha /" WHERE id = 401;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 402;
UPDATE books SET title = "Podliashe in umkum : notitsn fun hurbn." WHERE id = 403;
UPDATE books SET title = "Sefer Pragah = Prager yizker-bukh /" WHERE id = 404;
UPDATE books SET title = "Sefer Prushkov\, Nadz'in veha-sevivah /" WHERE id = 405;
UPDATE books SET title = "Pinkas Pruz'ani veha-sevivah : [tol]dot ve-zikaron li-kehilot she-hushmedu ba-Sho`ah /" WHERE id = 406;
UPDATE books SET title = "Pinkes fun finf fartilikte kehile`s : Pruzshene\, Bereze\, Maltsh\, Shershev\, Selts : zeyer oyfkum\, geshikhte un umkum /" WHERE id = 407;
UPDATE books SET title = "Kedoshe sheva kehilot : sefer zikaron lekehilot : Dolha\, Kusnica\, Zadne\, Kerecke\, Bereznik\, Lisicovo\, Sucha-Bronka /" WHERE id = 408;
UPDATE books SET title = "Sefer zikaron kehilat Proshnits /" WHERE id = 409;
UPDATE books SET title = "Sefer yizkor li-kedoshe `ir Pashyatsh : korbanot ha-sho'ah /" WHERE id = 410;
UPDATE books SET title = "Sefer Pshemishel /" WHERE id = 411;
UPDATE books SET title = "Sefer Pshitik : matsevet-zikaron li-kehilah Yehudit... /" WHERE id = 412;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 413;
UPDATE books SET title = "Yizker-bukh Polav /" WHERE id = 414;
UPDATE books SET title = "Pultusk : sefer zikaron /" WHERE id = 415;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 416;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 417;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 418;
UPDATE books SET title = "Gal`ed li-kehilat Ratsiyonz' /" WHERE id = 419;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 420;
UPDATE books SET title = "Radoshkovits : sefer zikaron /" WHERE id = 421;
UPDATE books SET title = "Rada'uts : kehilah Yehudit bi-tsemihatah uvi-sheki`atah /" WHERE id = 422;
UPDATE books SET title = "Dorot shel Yahadut ve-Tsiyonut Dorohoi : Saven\, Mikha'ilen\, Daraban\, Hertsah\, Rada'uts-Prut /" WHERE id = 423;
UPDATE books SET title = "Book of Radom : the story of a Jewish community in Poland destroyed by the Nazis /" WHERE id = 424;
UPDATE books SET title = "Radom /" WHERE id = 425;
UPDATE books SET title = "Seyfer Radom /" WHERE id = 426;
UPDATE books SET title = "Sefer yizkor li-kehilat Radomsk veha-sevivah /" WHERE id = 427;
UPDATE books SET title = "Radomishel rabati veha-sevivah : sefer zikaron" WHERE id = 428;
UPDATE books SET title = "Radzivilov : sefer zikaron /" WHERE id = 429;
UPDATE books SET title = "Sefer zikaron li-kehilat Radzimin /" WHERE id = 430;
UPDATE books SET title = "Sefer Radzin : yizker-bukh /" WHERE id = 431;
UPDATE books SET title = "Rahov-Annopol : pirke `edut ve-zikaron /" WHERE id = 432;
UPDATE books SET title = "Ratnah : sipurah shel kehilah Yehudit she-hushmedah /" WHERE id = 433;
UPDATE books SET title = "Yizkor-bukh Ratne : dos lebn un der umkum fun a Yidish shtetl in Volin /" WHERE id = 434;
UPDATE books SET title = "Sefer zikaron li-kehilat Ravah-Ruskah veha-sevivah /" WHERE id = 435;
UPDATE books SET title = "Geschichte der jüdischen gemeinde Rawitsch\," WHERE id = 436;
UPDATE books SET title = "Sefer zikaron li-kehilot Rembertov\, Okunyev\, Milosnah /" WHERE id = 437;
UPDATE books SET title = "Volt egyszer egy Dés... Bethlen\, Magyarlápos\, Retteg\, Nagyilonda és környéke." WHERE id = 438;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 439;
UPDATE books SET title = "Kehilat Rohatin veha-sevivah : `ir be-hayeha uvi-khilyonah /" WHERE id = 440;
UPDATE books SET title = "Rokitnah : (Vohlin) veha-sevivah ; sefer `edut ve-zikaron /" WHERE id = 441;
UPDATE books SET title = "Rovneh : sefer zikaron /" WHERE id = 442;
UPDATE books SET title = "Sefer zikaron li-kehilat Roz'an `al ha-Narev /" WHERE id = 443;
UPDATE books SET title = "Sefer-zikaron li-kehilot Shts'uts'in\, Vasilishki\, Ostrin\, Novidbor\, Roz'anke /" WHERE id = 444;
UPDATE books SET title = "Roz'ishts' `ayarati = Mayn shtetl Rozshishtsh /" WHERE id = 445;
UPDATE books SET title = "Sefer yizkor Rozvadov veha-sevivah /" WHERE id = 446;
UPDATE books SET title = "Sefer Rubiz'evits'\, Derevnah veha-sevivah /" WHERE id = 447;
UPDATE books SET title = "Sefer zikhron Stoyebts-Sverz'no veha-`ayarot ha-semukhot Rubezevits\, Derevno\, Nalibok /" WHERE id = 448;
UPDATE books SET title = "Rudki\, sefer yizkor li-Yehude Rudki veha-sevivah /" WHERE id = 449;
UPDATE books SET title = "Sefer le-zikhron kedoshe Ruskovah ve-Zoblas mehoz Marmarosh : she-nispu...bi-shenot ha-Sho'ah... /" WHERE id = 450;
UPDATE books SET title = "Ruz'inoi : sefer zikaron li-kehilat Ruz'inoi veha-sevivah /" WHERE id = 451;
UPDATE books SET title = "Sefer Ripin /" WHERE id = 452;
UPDATE books SET title = "Kehilat Risha : sefer zikaron /" WHERE id = 453;
UPDATE books SET title = "Sefer Strizov veha-sevivah /" WHERE id = 454;
UPDATE books SET title = "Örökmeécses : Sahy-Ipoolyság és környéke /" WHERE id = 455;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 456;
UPDATE books SET title = "Sefer Yehude Sala´z-Siladi : toldotehem\, kehilotehem\, mishpehotehem : binyan u-ferihah\, hurban u-kemilah /" WHERE id = 457;
UPDATE books SET title = "Sefer Sambor-Stari-Sambor : pirke `edut ve-zikaron... /" WHERE id = 458;
UPDATE books SET title = "`Et ezkerah : sefer kehilat Tsoizmir (Sandomiyez') /" WHERE id = 459;
UPDATE books SET title = "Sanok : sefer zikaron li-kehilat Sanok veha-sevivah /" WHERE id = 460;
UPDATE books SET title = "Sefer yizkor li-kehilat Sarnaki" WHERE id = 461;
UPDATE books SET title = "Sefer yizkor li-kehilat Sarni /" WHERE id = 462;
UPDATE books SET title = "Vanished communities in Hungary : the history and tragic fate" WHERE id = 463;
UPDATE books SET title = "Dorot shel Yahadut ve-Tsiyonut Dorohoi : Saven\, Mikha'ilen\, Daraban\, Hertsah\, Rada'uts-Prut /" WHERE id = 464;
UPDATE books SET title = "Sefer Vaidislav-Sendzishuv : mif`al ha-Va`ad ha-tsiburi shel yots'e Vaidislav-Sandzishov ba-Arets uvi-tefutsot." WHERE id = 465;
UPDATE books SET title = "Pinkes fun finf fartilikte kehile`s : Pruzshene\, Bereze\, Maltsh\, Shershev\, Selts : zeyer oyfkum\, geshikhte un umkum /" WHERE id = 466;
UPDATE books SET title = "Sefer Serotsk /" WHERE id = 467;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 468;
UPDATE books SET title = "Hurbn Glubok\, Sharkoystsene\, Dunilovitsh\, Postav\, Droye\, Kazan : dos lebn un umkum fun yidishn shtetlekh in Vaysrusland-Lite (Vilne gegent) /" WHERE id = 469;
UPDATE books SET title = "Hurban Kehilat Shetsotsin (Byalist) = Der hurbn fun der Shtsutsiner kehile (Byalistoker voyevudztve)." WHERE id = 470;
UPDATE books SET title = "Pinkes fun finf fartilikte kehile`s : Pruzshene\, Bereze\, Maltsh\, Shershev\, Selts : zeyer oyfkum\, geshikhte un umkum /" WHERE id = 471;
UPDATE books SET title = "Shpolah : masekhet haye Yehudim be-`ayarah." WHERE id = 472;
UPDATE books SET title = "Yehude Bulgaryah : kehilat Shumlah /" WHERE id = 473;
UPDATE books SET title = "Shumsk : sefer zikaron li-kedoshe Shumsk she-nispu be-Sho'at ha-Natsim bi-shenat 1942 /" WHERE id = 474;
UPDATE books SET title = "Pinkas Shavli : yoman mi-geto Lita'i\, 1941-1944 /" WHERE id = 475;
UPDATE books SET title = "Sefer yizkor li-kehilat Shedlets : li-shenat arba` `e´sreh le-hurbanah /" WHERE id = 476;
UPDATE books SET title = "Sefer zikaron li-kehilat Shedlishtse vehaseviva /" WHERE id = 477;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 478;
UPDATE books SET title = "Kehilat Semyatits' /" WHERE id = 479;
UPDATE books SET title = "Kehilat Sherpts : sefer zikaron /" WHERE id = 480;
UPDATE books SET title = "Sefer Marmarosh : me'ah ve-shishim kehilot kedoshot be-yishuvan uve-hurbanan /" WHERE id = 481;
UPDATE books SET title = "Skala /" WHERE id = 482;
UPDATE books SET title = "Death of a shtetl /" WHERE id = 483;
UPDATE books SET title = "Es shtarbt a shtetl : megile`s Skalat /" WHERE id = 484;
UPDATE books SET title = "Skalat : kovets zikaron li-kehilah she-harvah ba-Sho'ah /" WHERE id = 485;
UPDATE books SET title = "Seyfer Skernyevits : le-zeykher der fartilikter kehileh kdosheh /" WHERE id = 486;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 487;
UPDATE books SET title = "Pinkas Slonim /" WHERE id = 488;
UPDATE books SET title = "Pinkas Slutsk u-venoteha." WHERE id = 489;
UPDATE books SET title = "Smorgon\, mehoz Vilna : sefer `edut ve-zikaron /" WHERE id = 490;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 491;
UPDATE books SET title = "Pinkes Sokhatshev /" WHERE id = 492;
UPDATE books SET title = "Ilan ve-shorashav : sefer korot Tal : Zofyovkah--Ignatovkah /" WHERE id = 493;
UPDATE books SET title = "Sefer Sokal /" WHERE id = 494;
UPDATE books SET title = "Skori'an (Besarabyah) : be-vinyanah uve-hurbanah /" WHERE id = 495;
UPDATE books SET title = "Sokolievka/Justingrad : a century of struggle and suffering in a Ukrainian shtetl\, as recounted by survivors to its scattered descendants /" WHERE id = 496;
UPDATE books SET title = "Sefer Sokolkah : dos bukh fun Sokolke (`a.y. Irgun Yots'e Sokolkah be-Yi´sra'el) /" WHERE id = 497;
UPDATE books SET title = "Mayn horev shtetl Sokolov : shilderungen\, bilder un portretn fun a shtot umgekumene Yidn /" WHERE id = 498;
UPDATE books SET title = "Sefer ha-zikaron Sokolov-Podliask /" WHERE id = 499;
UPDATE books SET title = "Yoyvl-bukh : gevidmet dem ondenken fun di kdoyshim un martirer fun Sokolov /" WHERE id = 500;
UPDATE books SET title = "Sefer zikaron li-kedoshe Sokoli = Sokoler yizker-bukh /" WHERE id = 501;
UPDATE books SET title = "Sokoli ba-ma'avak le-hayim /" WHERE id = 502;
UPDATE books SET title = "Korot `ayarah ahat : megilat ha-´sig´sug veha-hurban shel kehilat Sopotkin." WHERE id = 503;
UPDATE books SET title = "Sefer Sosnovits veha-sevivah be-Zaglembiyah /" WHERE id = 504;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 505;
UPDATE books SET title = "Sefer Virzbnik-Starakhovits /" WHERE id = 506;
UPDATE books SET title = "Sefer Stashov /" WHERE id = 507;
UPDATE books SET title = "`Ayaratenu Stepan /" WHERE id = 508;
UPDATE books SET title = "Pinkes Stok : (bay Vengrov) : matseyva`s netsah /" WHERE id = 509;
UPDATE books SET title = "Stolin : sefer-zikaron li-kehilat Stolin veha-sevivah /" WHERE id = 510;
UPDATE books SET title = "Sefer zikhron Stoyebts-Sverz'no veha-`ayarot ha-semukhot Rubezevits\, Derevno\, Nalibok /" WHERE id = 511;
UPDATE books SET title = "Sefer yizkor li-kehilat Trembovlah Strusov ve-Yanov veha-sevivah." WHERE id = 512;
UPDATE books SET title = "Sefer Stri /" WHERE id = 513;
UPDATE books SET title = "Stshegove yizkor-bukh." WHERE id = 514;
UPDATE books SET title = "Sefer Strizov veha-sevivah" WHERE id = 515;
UPDATE books SET title = "Book of Stryzow and vicinity /" WHERE id = 516;
UPDATE books SET title = "Sefer zikaron li-kehilot Vadovitseh\, Andrikhov\, Kalvaryah\, Mishlenits\, Suka /" WHERE id = 517;
UPDATE books SET title = "Hurbn Sukhovolie : le-zikoron fun a Yidish shtetl tsvishn Bialistok un Grodne /" WHERE id = 518;
UPDATE books SET title = "Sefer Suhovolah. Dos bukh fun Sukhovolye." WHERE id = 519;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 520;
UPDATE books SET title = "Yizker-bukh Suvalk un di arumike shtetlekh : Baklerove\, Vizshan\, Yelineve\, Sayni\, Punsk\, Psherosle\, Filipove\, Krasnopole\, Ratsk /" WHERE id = 521;
UPDATE books SET title = "Sefer zikaron le-`esrim ve-shalosh kehilot she-nehrevu be-ezor Shevintsyan /" WHERE id = 522;
UPDATE books SET title = "`Ayaratenu Svir /" WHERE id = 523;
UPDATE books SET title = "Hayoh hayetah `ayarat Svir : ben shete milhamot ha-`olam /" WHERE id = 524;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 525;
UPDATE books SET title = "Sefer zikaron li-kehilat Shebreshin /" WHERE id = 526;
UPDATE books SET title = "Pinkas Shts'kots'in : Shtshekotshiner yizker-bukh ; lebn un umkum fun a Yidish shtetl /" WHERE id = 527;
UPDATE books SET title = "Sefer-zikaron li-kehilot Shts'uts'in\, Vasilishki\, Ostrin\, Novidbor\, Roz'anke /" WHERE id = 528;
UPDATE books SET title = "Kehilat Shrensk veha-sevivah : sefer zikaron." WHERE id = 529;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 530;
UPDATE books SET title = "Shidlovtser yizker-bukh /" WHERE id = 531;
UPDATE books SET title = "Memorial book Szydlowiec /" WHERE id = 532;
UPDATE books SET title = "Torne : kiyem un hurbn fun a Yidisher shtot /" WHERE id = 533;
UPDATE books SET title = "Tashnad : te'ur histori le-zekher kehilat Tashnad (Transilvanyah) veha-sevivah vi-yeshivat Maharam Brisk\, mi-reshitan ve-`ad le-ahar yeme h" WHERE id = 534;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 535;
UPDATE books SET title = "Telekhan /" WHERE id = 536;
UPDATE books SET title = "Sefer Telz (Lita) : matsevet zikaron li-kehilah kedoshah = Telsiai book /" WHERE id = 537;
UPDATE books SET title = "Sefer yizkor li-kehilat Trembovlah Strusov ve-Yanov veha-sevivah." WHERE id = 538;
UPDATE books SET title = "Tarnopol /" WHERE id = 539;
UPDATE books SET title = "´Saloniki : `ir va-'em be-Yi´sra'el." WHERE id = 540;
UPDATE books SET title = "Zikhron ´Saloniki : gedulatah ve-hurbanah shel Yerushalayim de-Balkan\, ha-`orekh /" WHERE id = 541;
UPDATE books SET title = "Volt egyszer egy Dés... Bethlen\, Magyarlápos\, Retteg\, Nagyilonda és környéke." WHERE id = 542;
UPDATE books SET title = "Tlumats' = Tolmitsh = Tlumacz : sefer `edut ve-zikaron /" WHERE id = 543;
UPDATE books SET title = "Sefer zikaron shel Tomashov-Lub /" WHERE id = 544;
UPDATE books SET title = "Tomashover Lub[lin] yizker bukh : poh nikhtav toldot yishuv Yehudi = Tomashov deLublin mi-yom hivasdah ve-`ad hurbanah ..." WHERE id = 545;
UPDATE books SET title = "Sefer zikaron li-kehilat Tomashov-Mazovyetsk /" WHERE id = 546;
UPDATE books SET title = "Story and source of the Jewish community of Topoltchany /" WHERE id = 547;
UPDATE books SET title = "Sefer Tlustah /" WHERE id = 548;
UPDATE books SET title = "Troki." WHERE id = 549;
UPDATE books SET title = "Kehilat Tshebin /" WHERE id = 550;
UPDATE books SET title = "Yehude Tuts'in u-Kripah mul rotshehem : `e´srim ve-arba` `eduyot" WHERE id = 551;
UPDATE books SET title = "Sefer zikaron li-kehilat Turek veli-kedosheha." WHERE id = 552;
UPDATE books SET title = "Kehilot Turets ve-Yeremits : sefer zikaron /" WHERE id = 553;
UPDATE books SET title = "Turkah : sefer zikaron /" WHERE id = 554;
UPDATE books SET title = "Sefer Turbin : pinkas zikaron /" WHERE id = 555;
UPDATE books SET title = "Zikhron netsah la-kehilot ha-kedoshot Halmin-Turts veha-sevivah asher nehrevu ba-sho'ah : hantsahat kehilot ha-kodesh Halmin-Turts veha-se" WHERE id = 556;
UPDATE books SET title = "Sefer Tiktin /" WHERE id = 557;
UPDATE books SET title = "Pinkas Tishivits /" WHERE id = 558;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 559;
UPDATE books SET title = "Sefer zikaron li-kehilat Hivniv (Uhnov) veha-sevivah /" WHERE id = 560;
UPDATE books SET title = "Sefer zikhronot shel kehilat...Oypsht /" WHERE id = 561;
UPDATE books SET title = "Sefer Yizkor : mukdash li-Yehude ha-`ayarot she-nispu ba-sho'ah ba-shanim 1939-44 : Linsk\, Istrik\, Beligrod\, Litovisk veha-sevivah /" WHERE id = 562;
UPDATE books SET title = "Kehilat Ustilah be-vinyanah uve-hurbanah /" WHERE id = 563;
UPDATE books SET title = "Yizkor-bukh Utian un umgegnt /" WHERE id = 564;
UPDATE books SET title = "Ungvar /" WHERE id = 565;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 566;
UPDATE books SET title = "Ayarah bi-lehavot : sefer zikaron li-kehilat Olkenik\, pelakh Vilnah." WHERE id = 567;
UPDATE books SET title = "Voloz'in : sifrah shel ha- `ir ve-shel Yeshivat `Ets Hayim /" WHERE id = 568;
UPDATE books SET title = "Debreceni zsidók száz éve : a mártirhalállt halt debreceni és környékbeli zsidók emlékére /" WHERE id = 569;
UPDATE books SET title = "Vasi zsidók emlékére a mártirhalált szenvedett vasmegyei zsidóságnak /" WHERE id = 570;
UPDATE books SET title = "Sefer-zikaron li-kehilot Shts'uts'in\, Vasilishki\, Ostrin\, Novidbor\, Roz'anke /" WHERE id = 571;
UPDATE books SET title = "Volkovisk : sipurah shel kehilah Yehudit-Tsiyonit : hushmedah ba-Sho'ah\, 1941-1943 /" WHERE id = 572;
UPDATE books SET title = "Volkovisker yisker-bukh /" WHERE id = 573;
UPDATE books SET title = "Mosti-Vi'elkeh : hayah ve-hurbanah shel kehilah Yehudit." WHERE id = 574;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 575;
UPDATE books SET title = "Sefer Vidz : `ayarah be-hayeha uve-khilyonah /" WHERE id = 576;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 577;
UPDATE books SET title = "Sefer zikaron kehilat Vilaikah : ha-mehozit\, pelekh Vilnah /" WHERE id = 578;
UPDATE books SET title = "Hurbn Vilne : umkum fun di Yidn in Vilne un Vilner gegnt ... : zamlung fun eydus : bavayzn oder dokumentn." WHERE id = 579;
UPDATE books SET title = "Yerusholaim de-Lita: ilustrirt un dokumentirt = Jerusalem of Lithuania: illustrated and documented ... /" WHERE id = 580;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 581;
UPDATE books SET title = "Vishnivits : sefer zikaron li-kedoshe Vishnivits she-nispu be-sho'at ha-natsim /" WHERE id = 582;
UPDATE books SET title = "Vishnivah ke-fi she-hayetah ve-enenah `od -- : sefer zikaron /" WHERE id = 583;
UPDATE books SET title = "Vitebsk amol : geshikhte\, zikhroyne`s\, hurbn /" WHERE id = 584;
UPDATE books SET title = "Vitebsk /" WHERE id = 585;
UPDATE books SET title = "Sefer kehilat Suvalk u-venoteha : Baklorovah\, Viz'an\, Saini\, Punsk\, Filipovah\, Psheroshlah\, Ratsk /" WHERE id = 586;
UPDATE books SET title = "Sefer Vladimerets : gal`ed le-zekher `irenu /" WHERE id = 587;
UPDATE books SET title = "Pinkas Ludmir : sefer-zikaron li-kehilat Ludmir." WHERE id = 588;
UPDATE books SET title = "Voronovah : sefer zikaron li-kedoshe Voronovah she-nispu be-sho'at ha-Natsim ba-shanim 1941-1944 /" WHERE id = 589;
UPDATE books SET title = "Sefer zikaron li-kehilat Selish veha-sevivah /" WHERE id = 590;
UPDATE books SET title = "`Ayaratenu Visotsk : sefer zikaron /" WHERE id = 591;
UPDATE books SET title = "Sefer zikaron li-kehilot Vadovitseh\, Andrikhov\, Kalvaryah\, Mishlenits\, Suka /" WHERE id = 592;
UPDATE books SET title = "Varshah." WHERE id = 593;
UPDATE books SET title = "Yizkor-bukh = Izkor buj: Varshe /" WHERE id = 594;
UPDATE books SET title = "`Arim ve-imahot be-Yisra'el : matsevet kodesh li-kehilot..." WHERE id = 595;
UPDATE books SET title = "Pinkes Vashilkover yizker bukh : a spetsyele oysgabe vegn lebn\, mord un toyt fun a Yidishn yishev : analogishe geshikhtlekhe ophandlungen in" WHERE id = 596;
UPDATE books SET title = "Kehilat Vengrov : sefer zikaron /" WHERE id = 597;
UPDATE books SET title = "Kehilat Vilits'kah : sefer zikaron." WHERE id = 598;
UPDATE books SET title = "Sefer zikaron li-kehilat Vyelun /" WHERE id = 599;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 600;
UPDATE books SET title = "Virushov : sefer yizkor /" WHERE id = 601;
UPDATE books SET title = "Sefer Virzbnik-Starakhovits /" WHERE id = 602;
UPDATE books SET title = "Pinkes Zshirardov\, Amshinov un Viskit : Yizker-bukh" WHERE id = 603;
UPDATE books SET title = "Sefer Vayslits : sefer `edut ve-zikaron = Dos Vayslitser yizkor-bukh /" WHERE id = 604;
UPDATE books SET title = "Vlotslavek veha-sevivah : sefer zikaron /" WHERE id = 605;
UPDATE books SET title = "Sefer zikaron Vlodavah veha-sevivah Sobibor /" WHERE id = 606;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 607;
UPDATE books SET title = "Sefer Vaidislav-Sendzishuv : mif`al ha-Va`ad ha-tsiburi shel yots'e Vaidislav-Sandzishov ba-Arets uvi-tefutsot." WHERE id = 608;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 609;
UPDATE books SET title = "Yizker-bukh tsum fareybikn der ondenk fun der horev gevorener Yidisher kehile Voyslavits /" WHERE id = 610;
UPDATE books SET title = "Volbrom `irenu; sefer-yizkor li-shenat ha-`e´srim le-hurban ha-ayom shel ha-`ir she-hayitah moladetenu ba-`avar /" WHERE id = 611;
UPDATE books SET title = "Sefer zikaron kehilat Volomin /" WHERE id = 612;
UPDATE books SET title = "Visoke-Mazovyetsk yizkor-bukh /" WHERE id = 613;
UPDATE books SET title = "Transliterations of necrologies from the yizkor (memorial) books of the towns Serock\, Wlodowa\, Tyszowce\, Wielun\, Wysokie Mazowieckie\, Szydlowiec\, Wod" WHERE id = 614;
UPDATE books SET title = "Sefer Vishkov /" WHERE id = 615;
UPDATE books SET title = "Vishogrod : sefer zikaron li-kedoshe Vishogrod she-nispu be-sho'at ha-Natsim bi-shenat 1939-1945 /" WHERE id = 616;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 617;
UPDATE books SET title = "Yad le-Yedinits : sefer zikaron li-Yehude Yedinits Besaravyah /" WHERE id = 618;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 619;
UPDATE books SET title = "Zabludove : yizkor bukh ; di geshikhte fun der yidisher kehile Zabludove fun ir bereshit biz ir fartilikung durkh di natsishe rotshim /" WHERE id = 620;
UPDATE books SET title = "Pinkes Zaglembye /" WHERE id = 621;
UPDATE books SET title = "Sefer Zikhron kedoshim li-Yehude Karpatoros-Maramuresh : le-hantsahat zekher ha-kehilot ha-kedoshot ... /" WHERE id = 622;
UPDATE books SET title = "Sefer Novi-Targ veha-sevivah : Zakopanah\, Ts'arni Dunayets\, Rabkah\, Yordanuv\, Shts'avnitsah\, Kroshts'enko\, Yablonkah\, Makov-Podhalanski /" WHERE id = 623;
UPDATE books SET title = "Sefer Zambrov : Zembrove : zikaron li-kehilat ha-kodesh she-hushmedah H. y. d. : tsum ondenk der fartilikter kehileh H. y. d. /" WHERE id = 624;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 625;
UPDATE books SET title = "Pinkes Zamoshtsh : yizker bukh tsum fuftsntn yortsayt (1942-1957) nokh der ershter shehite fun di Zamoshtsher Yidn /" WHERE id = 626;
UPDATE books SET title = "Zamoshts bi-ge'onah uve-shivrah." WHERE id = 627;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 628;
UPDATE books SET title = "Emesh Sho'ah-- : yad li-kehilot = Emesh Sho'ah-- : gevidment di kehile`s Braslav\, Opsah\, Okmenits\, Dubinah\, Zamosh\, Zarats'\, Ya'isi\, Yod\, Slobud" WHERE id = 629;
UPDATE books SET title = "Kehilat Z'arki : `ayarah be-hayeha uve-khilyonah /" WHERE id = 630;
UPDATE books SET title = "Sefer zikaron = andenk-bukh\, k. k. Zaviertshe veha-sevivah /" WHERE id = 631;
UPDATE books SET title = "Sefer Zbaraz' /" WHERE id = 632;
UPDATE books SET title = "Zdunskah-Volah /" WHERE id = 633;
UPDATE books SET title = "Yizker-bukh fun der Zshelekhover Yidisher kehile = Sefer yizkor li-kehilat Z'elihov /" WHERE id = 634;
UPDATE books SET title = "Sefer zikaron Zelvah /" WHERE id = 635;
UPDATE books SET title = "Sefer zikaron Zelvah = Zelva memorial book /" WHERE id = 636;
UPDATE books SET title = "Vanished communities in Hungary : the history and tragic fate" WHERE id = 637;
UPDATE books SET title = "Sefer Zgyerz' : mazkeret netsah li-kehilah Yehudit be-Polin = Sefer Zgerzsh : tsum ondenk fun a yidisher kehile in Poyln = Zgierz : ksi¸ega pami¸" WHERE id = 638;
UPDATE books SET title = "Sefer Z'eludok ve-Orlovah : gal`ed le-zikaron /" WHERE id = 639;
UPDATE books SET title = "Sefer Z'olkiv : (kiryah-ni´sgavah) /" WHERE id = 640;
UPDATE books SET title = "Kaminits-Podolsk & its environs : a memorial book of the Jewish communities in the cities of Kaminits-Podolsk\, Balin\, Dunivits\, Zamekhov\, Zhvanets\, M" WHERE id = 641;
UPDATE books SET title = "Yizkor dem ondeynken Zshitomirer kdoyshim." WHERE id = 642;
UPDATE books SET title = "Pinkas Zinkov : gedenkbukh /" WHERE id = 643;
UPDATE books SET title = "Sefer le-zikhron kedoshe Ruskovah ve-Zoblas mehoz Marmarosh : she-nispu...bi-shenot ha-Sho'ah... /" WHERE id = 644;
UPDATE books SET title = "Zvoliner yizker bukh /" WHERE id = 645;
UPDATE books SET title = "Herinneringsboek Joods Zwolle 1940-1945 /" WHERE id = 646;
UPDATE books SET title = "Sefer Z'ihlin /" WHERE id = 647;
UPDATE books SET title = "Pinkes Zshirardov\, Amshinov un Viskit : Yizker-bukh" WHERE id = 648;
UPDATE books SET title = "The Memorial Book for the Jewish Community of Yurburg" WHERE id = 649;
UPDATE books SET title = "Khashchevato : main shteitele : kniga pamiata" WHERE id = 650;
UPDATE books SET title = "Chust and Vicinity : a Memorial Book of the Community" WHERE id = 651;
UPDATE books SET title = "Sefer ha-zikaron shel Yehude Vatrah-Dorne veha-sevivah" WHERE id = 652;
UPDATE books SET title = "The Volkovysk Memorial Book." WHERE id = 653;
UPDATE books SET title = "Zuromin\, Polin :sipurah shel kehilah she-nikretah." WHERE id = 654;
